name:                taskrunner
version:             0.3.0.0
github:              "githubuser/taskrunner"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/taskrunner#readme>

dependencies:
- base >= 4.7 && < 5
- universum
- containers
- text
- filepath
- directory
- data-default
- bytestring
- unix
- process
- async
- time
- temporary
- optparse-applicative
- filelock
- Glob
- file-embed
- aeson
- cryptonite
- resourcet
- amazonka
- amazonka-core
- amazonka-s3
- amazonka-s3-streaming
- zstd
- conduit-zstd
- tar
- tar-conduit
- conduit
- conduit-combinators
- conduit-extra
- network-uri
- random
- lens
- jwt
- http-client
- http-client-tls
- http-types

default-extensions:
  - OverloadedStrings
  - DuplicateRecordFields
  - OverloadedRecordDot
  - DerivingStrategies
  - DerivingVia
  - DeriveGeneric
  - GeneralizedNewtypeDeriving
  - BlockArguments
  - FlexibleContexts
  - TupleSections
  - NamedFieldPuns
  - LambdaCase
  - MultiWayIf
  - NoImplicitPrelude
  - ScopedTypeVariables
  - MultiParamTypeClasses
  - FunctionalDependencies
  - TypeSynonymInstances
  - FlexibleInstances
  - FlexibleContexts
  - ExplicitNamespaces
  - PatternSynonyms
  - ImportQualifiedPost
  - OverloadedLabels
  - TypeApplications
  - DeriveAnyClass
  - ViewPatterns
  - DataKinds
  - TypeFamilies
  - RecordWildCards
  - DeriveTraversable
  - DeriveFoldable
  - TypeOperators

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Werror=incomplete-record-updates
- -Werror=incomplete-uni-patterns
- -Wmissing-home-modules
- -Werror=partial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  ghc-options: -O

executables:
  taskrunner:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    # Note: -threaded is actually needed even if we don't need multicore, see https://hackage.haskell.org/package/process-1.6.20.0/docs/System-Process.html#v:waitForProcess
    # > GHC Note: in order to call waitForProcess without blocking all the other threads in the system, you must compile the program with -threaded.
    - -threaded
    - -O
    dependencies:
    - taskrunner

tests:
  taskrunner-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    dependencies:
    - taskrunner
    - tasty
    - tasty-golden
